apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-provisioner
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-provisioner
rules:
  - apiGroups: ["minio.sonne.zone"]
    resources:
      - miniobuckets
      - miniobuckets/status
      - miniousers
      - miniousers/status
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-provisioner
subjects:
  - kind: ServiceAccount
    name: minio-provisioner
    namespace: {{ .Values.namespace }}
